### ISSUE TITLE
Code samples contain zero-width space chars

### ISSUE THREAD

**Issue by jasonstitt** [keycloak/keycloak-documentation#1328]
### Describe the bug

Code samples in the docs can't be copied and pasted and run because they contain invalid chars (specifically zero-width spaces)

### Version

n/a

### Expected behavior

Go to e.g. https://www.keycloak.org/docs/latest/securing_apps/#usage-2 and copy the code into a file. It should be able to run.

### Actual behavior

```
/Users/xxx/keycloak-err.js:1
​var session = require('express-session');


SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

### How to Reproduce?

^

**Comment by stianst** [comment]
The documentation has been moved to [the main Keycloak repository](https://github.com/keycloak/keycloak/tree/main/docs/documentation).

Closing this issue as its been around for a long time without any updates. If still relevant please open a new issue in [the main repository](https://github.com/keycloak/keycloak/issues).
